trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Install dependencies
- script: |
    npm install
  displayName: 'npm install'

# (Optional) If you have a front-end build process, add the build step.
# - script: |
#     npm run build
#   displayName: 'Build front-end'

# Publish to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: '3bb8a984-75e7-48a4-b1dc-94cdcef74bb9'  # Replace with your Azure subscription service connection
    appName: 'nodejs-cicd'  # Replace with your Azure Web App name
    package: $(System.DefaultWorkingDirectory)  # Path to the folder with your Node.js app
    startUpCommand: 'npm start'  # Ensure to start your app with npm start command
  displayName: 'Deploy to Azure Web App'

# Optionally, you can add steps for running tests, saving build artifacts, etc.

