name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]  # Testing across multiple Node.js versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npm run lint

    - name: Format code
      run: npm run format

    - name: Run tests
      run: |
        echo "No test script defined. Please add tests in package.json." # Placeholder

