name: Node.js CI/CD to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npm run lint

    - name: Format code
      run: npm run format

    - name: Run tests
      run: |
        echo "No test script defined. Please add tests in package.json."

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: WebApp-Node-RG-Devansh-POC
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
        package: .

